### ISSUE TITLE
consul reload fails during packer build

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/fpco-salt-formula#102]
consul isn't running, so the `consul reload` fails. review the situation and see if there's a simple way to address the error.

**Comment by lpaulmp** [comment]
The same error I got in vagrant when it executed saltstack, this was addressed in the PR #155.
The issues were that consul depends on consul-template to initialize.

**Comment by ketzacoatl** [comment]
Is this resolved when PR #155 is merged?

**Comment by lpaulmp** [comment]
No, the #151 fixed this issue we can close.
