### ISSUE TITLE
super basic tests for hashistack

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/fpco-salt-formula#126]
## Requirements

* keep it really simple, write a shell script that runs a list of tests
* run the list of tests below
* it should be relatively easy to run this script at the end of Vagrant provisioning, or at some other time with the formula installed.
* It should be possible to run the script locally on the VM or on a host that has the formula installed (targeting itself).
* It should also be possible to run the script from a developer workstation (targeting the VM or another remote host)

## setup a way to run the following tests

* `salt-call --local state.sls consul.service,nomad.service test=True`
* `consul version`
* `consul members`
* `consul kv list`
* `nomad version`
* `nomad status`
* `nomad agent-info`
* `nomad server members`
* `nomad node status`

**Comment by lpaulmp** [comment]
Closed this issue via https://github.com/fpco/fpco-salt-formula/pull/156
