### ISSUE TITLE
add TLS to workflow for vagrant workspace

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/fpco-salt-formula#141]
Our vagrant env creates a space for testing and R&D on the CM formula. As part of that, we want to emulate production deployments where possible. This generally includes TLS, and in the context of our test env, self-signed certs with a bootstrapped CA. See https://www.nomadproject.io/guides/securing-nomad.html for info on using `cfssl` as one method to generate the certs needed.

### Requirements

* update the workflow with Vagrant to include generating the CA and TLS certs our vagrant vm will need
* nomad, consul, and vault will all be getting TLS certs, we don't need to cover them all in this task, but the goal is to get the framework in place. start with one and add others if needed, or support them all if it's easy
* don't get into configuring each of the services using the TLS certs, focus on the workflow to generate certs that are configured correctly for use with these services
* docs to describe what to do and how to control/configure it
* make targets or shell scripts with helper utilities

**Comment by mcgirr** [comment]
I've added documentation for how to use this to the [readme](https://github.com/fpco/fpco-salt-formula/blob/52800c718313415ae2521dae0454dbb9e31e5ec6/README.md#tls-in-the-vagrant-test-env)

**Comment by ketzacoatl** [comment]
That reads well. Should we move this out of the root (where most paths are salt formula) to `test/tls`?
