### ISSUE TITLE
`Vagrantfile` for testing out `fpco-salt-formula`

### ISSUE THREAD

**Issue by kerscher** [fpco/fpco-salt-formula#99]
Users could then have the ability to:

```shell
git clone git@github.com:fpco/fpco-salt-formula
cd fpco-salt-formula
vagrant up
vagrant ssh
salt-call --local state.highstate
exit
vagrant destroy
```

**Comment by kerscher** [comment]
Perhaps `state.apply` instead since it seems that even Salt has changed from `state.highstate` to it to be clearer.

**Comment by ketzacoatl** [comment]
requirements:
* based on ubuntu xenial amd64
* do not use `bootstrap-salt-formula` for now, just do a simple install of saltstack and setup the formula in `fpco-salt-formula` to be available in `/srv/salt`
* should be easy to hack on the formula locally, and run tests on those updates in the VM

**Comment by ketzacoatl** [comment]
This is resolved, the basics are in place and look like:

```
vagrant up
```

or if need to re-provision:

```
vagrant up --provision
```
